// Code generated by hertz generator.

package score

import (
	"github.com/cloudwego/hertz/pkg/app"
	"judgeMore/biz/router/auth"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _scoreMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryscorebyscoreidMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(1)
}

func _queryscorebyeventidMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(1)
}

func _queryscorebystuidMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(1)
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _score0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _revisescoreMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(2)
}

func _query0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _scorerankMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _score1Mw() []app.HandlerFunc {
	// your code...
	return nil
}
